apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: {{ .Values.serviceType | default "ClusterIP" }}
  ports:
    - port: {{ .Values.servicePort | default 80 }}
      targetPort: 80
  selector:
    app: {{ .Values.name }}
